---
name: Build and Release Python Wheels

on:
  release:
    types: [published]
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0.0, v2.0.0, ...
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
      
      - name: Install Rust
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build

      - name: Build wheel
        run: |
          python -m build

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          path: |
            ./dist/*.whl

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          path: artifacts/

      - name: Move Wheel Files
        run: |
          mkdir -p wheels
          find artifacts -name '*.whl' -exec mv {} wheels/ \;

      - name: Upload Wheel Files
        run: |
          cd wheels
          ls -la
          for wheel in *.whl; do
            if [ -f "$wheel" ]; then
              echo "Uploading $wheel"
              curl -L \
                -X POST \
                -H "Accept: application/vnd.github+json" \
                -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                -H "X-GitHub-Api-Version: 2022-11-28" \
                -H "Content-Type: application/octet-stream" \
                "${{ github.event.release.upload_url }}=$(basename "$wheel")" \
                --data-binary "@$wheel"
            fi
          done

      # - name: Publish package
      #   uses: pypa/gh-action-pypi-publish@v1.8.11
      #   with:
      #     user: __token__
      #     password: ${{ secrets.PYPI_API_TOKEN }}
